### ISSUE TITLE
Solver for Deep net work?

### ISSUE THREAD

**Issue by ethanhe42** [imatge-upc/saliency-2016-cvpr#11]
Hi, I want to train the deep net on other dataset, how can I do that?

**Comment by kevinmcguinness** [comment]
Hi, 

Please take a look at the responses to these issues, which should hopefully help:

https://github.com/imatge-upc/saliency-2016-cvpr/issues/3
https://github.com/imatge-upc/saliency-2016-cvpr/issues/9

**Comment by ethanhe42** [comment]
Thanks
