### ISSUE TITLE
Regarding JuntingNet_iSUN.pickle input file

### ISSUE THREAD

**Issue by abhid95** [imatge-upc/saliency-2016-cvpr#14]
Hi, 
 We are trying to run your code. But we couldn't find "JuntingNet_iSUN.pickle" input file which is used in demo.py of shallow folder. Can you please help us by providing link to required file.
Thank you.

**Comment by junting** [comment]
Hello,
You can find the models here : [https://imatge.upc.edu/web/resources/end-end-convolutional-networks-saliency-prediction-software](url)
