### ISSUE TITLE
Question on two slices in the shallow net

### ISSUE THREAD

**Issue by NUAAXQ** [imatge-upc/saliency-2016-cvpr#19]
As I am a freshman on deep learning, I have a stupid question about the structure of your shallow net. There are two slices (slice1 and slice2) between the FC layer and the Maxout layer. I'm not clear about what they are. Are they the neurons in the hidden layer of the Maxout layer?
I will be very appreciate it if you can answer that.
![qq 20170308162057](https://cloud.githubusercontent.com/assets/16955487/23696268/ee047ea2-041d-11e7-8c11-5ffc120795b4.png)

**Comment by junting** [comment]
Hi @NUAAXQ ,

The Slice means to cut the output feature vector from la first FC layer into two slice, and then perform maxout operation between those two slices, for example you pick the value of the first position of both slices and only keep the biggest value. Hope this can help you.

Best,
Junting

**Comment by NUAAXQ** [comment]
Thanks for your reply. That really helps me.
