### ISSUE TITLE
Ready to make github repo public ?

### ISSUE THREAD

**Issue by xavigiro** [imatge-upc/saliency-2016-cvpr#2]
Dear @junting @kevinmcguinness @agilmor 

I have been working this morning mostly on the README.md of our recently accepted paper for CVPR 2016. I would like to make this repo public as soon as possible, so I would need you to tell me if you think that everything contained at the moment is enough to reproduce the experiments.

There are still some formatting issues I can improve, but I think that the basic is there. Also, please check in the source code and check that everything is in there.

Please answer this message with your OK as I will wait for it before launching the repo as well as a github project site based on the README.md you can find here.

What do you think ?

**Comment by kevinmcguinness** [comment]
@xavigiro Looks good to me. I added an SFI acknowledgement to the README btw.

**Comment by agilmor** [comment]
Hi, I've nothing else to say that thanks for the acknowledgements, I really apreciate it... but you don't need to! ;-)

And, just to add something: we should start thinking on adding a Dockerfile to any code we publish to make it more replicable... just for future code!

Congratulations for your work!

Albert

PS: By the way, I've asked @jpujal to provide you with a better resolution picture of himself... ;-)

**Comment by junting** [comment]
@xavigiro I think everything is perfect! Thank you Xavi!
