### ISSUE TITLE
help with the demo code

### ISSUE THREAD

**Issue by yasin06** [imatge-upc/saliency-2016-cvpr#5]
Hi, i am not very familier with the python code i might be doing something wrong,
but i'm receiving same output for each image with the (modified) demo code.
file names and indexes are fine, but the output gives same results for the images.

def saliencyPredictor(xt, net2, url, outUrl):
    y_pred_test = net2.predict(xt)
    i=0
    for file in glob.glob(url+"*.png"):  
      img = misc.imread(file)  
      tmp = y_pred_test[i].reshape(48,48)
      blured= ndimage.gaussian_filter(tmp, sigma=3)
      y = misc.imresize(blured,(img.shape[0],img.shape[1]))/255.
      #misc.imsave(outUrl + os.path.basename(file), y) 
      base = os.path.basename(file)
      scipy.io.savemat(outUrl + os.path.splitext(base)[0] + ".mat", {'y':y});
      i= i+1

**Comment by xavigiro** [comment]
Could you please indicate if you are trying to use our deep or our shallow convnet ?

**Comment by yasin06** [comment]
I am using JuntingNet SALICON,
I initialize the model only one time before all the predictions.

**Comment by junting** [comment]
Hello Yasin,

Could you please try to use the get_saliency.py from the deep network's folder. This script can also runs shallow network (You can just comment the part of deep network  and the import `from __init__ import SalNet`). I have just tried it ,and it is returning reasonable results.

**Comment by xavigiro** [comment]
Did you solve your issue @yasin06 ? In that case, I would ask you to close it.

**Comment by yasin06** [comment]
my apologies for the late reply, (need to switch tasks)
and thank you for your help,
after a couple python lib errors, i was finally able to run get_saliency and obtained some deep model results.
best regards.
